set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
set incsearch

syntax on

let g:vimexplorer_show_hidden = 1
let g:vimexplorer_show_header = 0

let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

colorscheme custom

command! Ex VimExplorer
