set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
set -s copy-command 'wl-copy -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'wl-copy -in -selection clipboard'

set -g mouse on

bind-key    Up    select-pane -U
bind-key    Down  select-pane -D
bind-key    Left  select-pane -L
bind-key    Right select-pane -R

set-option -g repeat-time 0
