[colors]
foreground=e4e4ef
background=181818

# regular
regular0=2e3436  # black
regular1=a40000  # red
regular2=4e9a06  # green
regular3=c4a000  # yellow
regular4=3465a4  # blue
regular5=75507b  # magenta
regular6=ce5c00  # cyan (orange-leaning in this palette)
regular7=babdb9  # white

# bright
bright0=555753   # bright black
bright1=ef2929   # bright red
bright2=8ae234   # bright green
bright3=fce94f   # bright yellow
bright4=729fcf   # bright blue
bright5=ad7fa8   # bright magenta
bright6=fcaf3e   # bright cyan (also orange-ish)
bright7=eeeeec   # bright white
